### PR TITLE
update scs to 2.1.2

### PR DESCRIPTION
**Pull request by kalmarek**

### CODE REVIEW

**Comment by kalmarek** [comment]
oh my BB stuff. Can we do something about it? @juan-pablo-vielma @blegat 
```julia
┌ Warning: julia version requirement for package BinaryBuilder not satisfied
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:153
┌ Warning: julia version requirement for package BinaryProvider not satisfied
└ @ Pkg.Operations /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Pkg/src/Operations.jl:153
ERROR: Unsatisfiable requirements detected for package ghr_jll [07c12ed4]:
 ghr_jll [07c12ed4] log:
 ├─possible versions are: 0.13.0 or uninstalled
 ├─restricted to versions 0.13.0-0.13 by BinaryBuilder [12aac903], leaving only versions 0.13.0
 │ └─BinaryBuilder [12aac903] log:
 │   ├─possible versions are: 0.2.5 or uninstalled
 │   └─BinaryBuilder [12aac903] is fixed to version 0.2.5
 └─restricted by julia compatibility requirements to versions: uninstalled — no versions left
```

**Comment by blegat** [comment]
I would rather follow the path of https://github.com/jump-dev/GLPK.jl/pull/131 than trying to sync this repo with yggdrasil

**Comment by blegat** [comment]
See https://github.com/JuliaPackaging/Yggdrasil#binaryproviderjl

**Comment by kalmarek** [comment]
very well! https://github.com/jump-dev/SCS.jl/pull/190

**Pull request closed without merging**
